# CRE PROJECT SETTINGS FILE
staging-settings:
  account:
    workflow-owner-address: "0xbd73D31277d69d2b80556068dbfcf9c3b5B2fd0b"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  account:
    workflow-owner-address: "0xbd73D31277d69d2b80556068dbfcf9c3b5B2fd0b"
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
